### ISSUE TITLE
Create Initial Project

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#1]
## Description
The base project needs to be set up. This will include creating a new project and generating setup files such as the C# sln.

## To-Do
- [x] Create new Godot project
- [x] Generate the sln for C#
- [x] Setup the .gitignore
- [x] Look into other setup files

**Comment by Ofthemasses** [comment]
This isn't finished
