### ISSUE TITLE
Create Basic Spawning System for Foxes

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#22]
## Description
Currently, the Path2D is a child of the fox node. This should change, as we will want multiple foxes following the path. We will also need a way to copy foxes so we can easily change how many spawn, and at what rate.

## To-Do
- [x] Detach fox node from the path, though make sure it still follows it
- [x] Create a second fox and add it to the path
- [x] Create a system that spawns foxes, remove the two earlier foxes
