### ISSUE TITLE
Format new assets into project

### ISSUE THREAD

**Issue by sam-mata** [toru-studio/COOP#27]
Several new assets have been created by **Holly** and should be 

## Assets to implement 
- [ ] Game over screen *(See #24)*.
- [ ] Play and pause buttons *(See #19 )*.
- [x] Basic tiling for path and grass.
- [ ] Health and Seed icons *(See #16 )*.
- [ ] General buttons for use in various UI elements.
- [x] Implement Light Chicken Asset

**Comment by Ofthemasses** [comment]
@nathanbridgeearney and I are hijacking this cause we need it done
