### ISSUE TITLE
Setup Trigger Mechanism and Queue for Fox Spawner

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#28]
## Description
Currently, the fox spawner will periodically spawn new foxes. This needs to be changed so foxes can be queued and spawned.

## To-Do
- [X] Create a queue for foxes
- [X] Create queuing method
- [x] Setup basic game state to test the class
