### ISSUE TITLE
Create Fox State and Health

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#33]
## Description
Foxes need to be reactive to our light. There are a few options for this, but I will draft out my own idea of it so we have something for now.

## To-Do
- [x] Convert Fox to C# class
- [x] Turn Fox into an abstract parent class
- [x] Blindness Level
- [x] Normal, Blind and Flee State
- [x] Test mouse click for blinding the foxes
