### ISSUE TITLE
Implement Currency Gameplay Loop

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#35]
## Description
Currently, there is no currency for players to buy towers with. We need to set up a counter, and a way to get currency. Some foxes will hold the currency, for now, a placeholder plant, and will drop it when blinded. Players can mouse over these plants to pick up their currency.

## To-Do
- [x] Implement currency counter
- [x] Create placeholder assets for plants held and on the floor
- [x] Create foxes that hold currency
- [x] Make foxes drop flowers on flee
- [x] On mouse over play animation and increase the counter
