### ISSUE TITLE
Implement Basic Fox Assets

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#46]
## Description
Change the current fox with the new art from Holly. Also, implement a walk cycle and blind fox.

## To-Do
- [x] Turn the fox textures into a sprite sheet.
- [x] Set up the walk cycle.
- [x] Switch to the blind fox when blinded

**Comment by Ofthemasses** [comment]
Need to implement flower foxes

## To-Do
- [x] Add flower foxes to the sprite sheet
- [x] Replace image loading system with sprite sheet change for flower foxes

**Comment by sam-mata** [comment]
#27 ???

**Comment by Ofthemasses** [comment]
> #27 ???

I checked that one and you didn't have a todo for the foxes. This is only for the foxes
