### ISSUE TITLE
Create Basic Tower

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#49]
## Description
Create a basic tower that tracks foxes. It should produce a cone that increases the foxes' blindness. There will be a centre beam and a "splash" cone. This will make the tower effective against the first fox, but will not be overpowered. Here is a sketch of the damage cone:
![image](https://github.com/toru-studio/COOP/assets/43369124/4627eb7f-815a-4094-801c-8aab2518598a)

## To-Do:
- [x] Create tower parent class
- [x] Create Basic Tower class
- [x] Make tower target the first fox in it's range
- [x] Create damage cone
- [x] Integrate hitboxes and damage
