### ISSUE TITLE
Make fleeing foxes run on the other side of the track to avoid overlap

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#57]
## Description
Fleeing foxes run underneath the other foxes. This needs to be changed as it is aesthetically unpleasing.

## To-Do
- [x] Touch up the foxes pathing
~~Offset the sprite of fleeing foxes~~
- [x] Created a new path for fleeing foxes
- [x] Changed foxes parent to the new path when fleeing
