### ISSUE TITLE
Implement Game Over

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#77]
## Description
The player needs health, and there needs to be a game over state.

## To-Do
- [x] Implement player health and counter
- [x] Implement game over state
- [x] Implement relevant assets
