### ISSUE TITLE
Fix Various Bugs

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#79]
## Description
This issue is a bit of a clean-up issue. We have a bug where foxes can go to the end of the track, we also have a bug with where the seeds are being sent to. I will update this with more To-Dos as I spot bugs.

## To-Do
- [x] Fix fox path inverting
- [x] Fix seed animation travel
- [x] Fix lightning tower panel crashes
