### ISSUE TITLE
Hook currency into tower panel

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/COOP#81]
## Description
The towers currently are free to place. They should require the amount of seeds the player currently has. There should also be an initial value of seeds (10) that the player can use at the start of the game.

## To-Do
- [x] Implement initial seed count
- [x] Towers take away from the seed count
- [x] Stop interaction with towers the player cannot afford
